=== jroddom0103/LMSGI/UD4/Actividades/Act5/Alumnado.dtd
<!ELEMENT Alumnado (alumnos)>
<!ELEMENT alumnos (alumno*)>
    <!ELEMENT alumno (nif, resultado, observaciones, ipmac)>
        <!ELEMENT nif (#PCDATA)>
        <!ELEMENT resultado (#PCDATA)>
        <!ELEMENT observaciones (#PCDATA)>
        <!ELEMENT ipmac (#PCDATA)>

=== jroddom0103/LMSGI/UD4/Actividades/Act5/AlumnadoDTD.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Alumnado SYSTEM "Alumnado.dtd">

<Alumnado>

    <alumnos>

        <alumno>
    
            <nif>57918411H</nif>
            <resultado>true</resultado>
            <observaciones></observaciones>
            <ipmac>ip</ipmac>
    
        </alumno>
    
        <alumno>
    
            <nif>98371531B</nif>
            <resultado>false</resultado>
            <observaciones>Ausencia prolongada.</observaciones>
            <ipmac>mac</ipmac>
    
        </alumno>
    
        <alumno>
    
            <nif>13896510E</nif>
            <resultado>true</resultado>
            <observaciones>Comportamiento ejemplar.</observaciones>
            <ipmac>mac</ipmac>
    
        </alumno>
    
    </alumnos>

</Alumnado>
