=== jroddom0103/LMSGI/UD4/Actividades/Act7/XSD/Editorial.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
	<xs:element name="Informe">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="regiones">
					<xs:complexType>
                            <xs:sequence>
                                <xs:element name="region" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="trimestres">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="trimestre" maxOccurs="unbounded">
                                                            <xs:complexType>
                                                                <xs:sequence>
                                                                    <xs:element name="libros_vendidos">
                                                                    </xs:element>
                                                                </xs:sequence>
                                                                <xs:attribute name="id" type="xs:string"/>
                                                            </xs:complexType>
                                                        </xs:element>
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                        <xs:attribute name="id" type="xs:string"/>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
				    </xs:element>
			    </xs:sequence>
            <xs:attribute name="descripcion" type="xs:string"/>
            <xs:attribute name="informeFecha" type="xs:string"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jroddom0103/LMSGI/UD4/Actividades/Act7/XML/Editorial-XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<Informe descripcion="Informe de ventas para las regiones Norte, Centro y Sur" informeFecha="30/12/2009" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="file:///C:/Users/jroddom0103/Desktop/1-DAW/Lenguaje/UD4/Actividades/Act7/XSD/Editorial.xsd">
    <regiones>

        <region id="Norte">
            <trimestres>

                <trimestre id="1">

                    <libros_vendidos>24000</libros_vendidos>

                </trimestre>

                <trimestre id="2">
                    
                    <libros_vendidos>38600</libros_vendidos>

                </trimestre>    

                <trimestre id="3">
                    
                    <libros_vendidos>NO_INFO</libros_vendidos>

                </trimestre>    

                <trimestre id="4">
                    
                    <libros_vendidos>NO_INFO</libros_vendidos>

                </trimestre>    

            </trimestres>
        </region>

        <region id="Centro">
            <trimestres>

                <trimestre id="1">

                    <libros_vendidos>NO_INFO</libros_vendidos>

                </trimestre>

                <trimestre id="2">
                    
                    <libros_vendidos>16080</libros_vendidos>

                </trimestre>    

                <trimestre id="3">
                    
                    <libros_vendidos>25000</libros_vendidos>

                </trimestre>    

                <trimestre id="4">
                    
                    <libros_vendidos>29000</libros_vendidos>

                </trimestre>  

            </trimestres>
        </region>

        <region id="Sur">
            <trimestres>

                <trimestre id="1">

                    <libros_vendidos>27000</libros_vendidos>

                </trimestre>

                <trimestre id="2">
                    
                    <libros_vendidos>31400</libros_vendidos>

                </trimestre>    

                <trimestre id="3">
                    
                    <libros_vendidos>40100</libros_vendidos>

                </trimestre>    

                <trimestre id="4">
                    
                    <libros_vendidos>30000</libros_vendidos>

                </trimestre>   

            </trimestres>
        </region>


    </regiones>

</Informe>
